# Generated by Django 3.0.2 on 2020-02-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=64)),
                ('project', models.CharField(max_length=64)),
                ('value', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=64)),
            ],
        ),
    ]
