# Generated by Django 3.0.2 on 2020-02-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='client',
            name='value',
            field=models.BigIntegerField(default=0),
        ),
    ]
